---
title: "BLOSUM62 matrox"
author: "Abril DH"
date: "3/21/2020"
output: html_document
---


```{r}
install.packages("tidyr")
```


```{r}
library(tidyverse)
library(tidyr)
library(purrr)
library(ggplot2)
library(dplyr)
```

```{r}
#Load the data
my_url <- "https://www.ncbi.nlm.nih.gov/Class/FieldGuide/BLOSUM62.txt"
bl62 <- read_table(file = my_url, comment = '#') %>%
  rename(aa = X1)
bl62
```

```{r}
#Wrangle and save the data
bl62 <- bl62 %>%
  select(aa:V) %>%
  slice(1:20) %>%
  write_tsv(path = "data/BLOSUM62_ncbi_USE_THIS.tsv")
bl62
```

```{r}
#create a PCA object
bl62_pca <- bl62 %>%
  select(-aa) %>%
  prcomp(center = TRUE, scale = TRUE)
bl62_pca
```
```{r}
#Make a screen plot using broom to tidy
bl62_pca %>%
  tidy() %>% 
  ggplot(aes(x = PC, y = percent)) +
  geom_col() +
  theme_bw()
```
```{r}
#Augment using broom
bl62_pca_aug <- bl62_pca %>%
  augment(bl62)
bl62_pca_aug
```
```{r}
#Add some chemical classes
get_chem_class <- function(x){
  chem_cols <- c("A" = "Hydrophobic", "R" = "Basic", "N" = "Neutral", "D" = "Acidic",
                 "C" = "sulphur", "Q" = "Neutral", "E" = "Acidic", "G" = "Polar",
                 "H" = "Basic", "I" = "Hydrophobic", "L" = "Hydrophobic", "K" = "Basic",
                 "M" = "sulphur", "F" = "Hydrophobic", "P" = "Hydrophobic", "S" = "Polar",
                 "T" = "Polar", "W" = "Hydrophobic", "Y" = "Polar", "V" = "Hydrophobic")
  return(factor(chem_cols[x]))
}
```

```{r}
bl62_pca_aug <- bl62_pca_aug %>% 
  mutate(chem_class = get_chem_class(aa))
```

```{r}
bl62_pca_aug %>% select(aa, chem_class)
```

```{r}
#Plot the PCA
bl62_pca_aug %>% 
  ggplot(aes(x = .fittedPC1, y = .fittedPC2, label = aa, colour = chem_class)) +
  geom_text() +
  theme(legend.position = "bottom")
```

```{r}
bl62_pca_aug %>% pull(chem_class) %>% levels
```

```{r}
x <- bl62_pca %>% 
  tidy("pcs") %>% 
  filter(PC==1) %>% 
  pull(percent)
x <- str_c("PC1 (", round(x*100, 2), "%)")
y <- bl62_pca %>% 
  tidy("pcs") %>% 
  filter(PC==2) %>% 
  pull(percent)
y <- str_c("PC2 (", round(y*100, 2), "%)")
```

```{r}
bl62_pca_aug %>% 
  ggplot(aes(x = .fittedPC1, y = .fittedPC2,
             label = aa, colour = chem_class)) +
  geom_label_repel() + # library("ggrepel") trick here
  theme(legend.position = "bottom") +
  scale_colour_manual(values = c("red", "blue", "black",
                                 "purple", "green", "yellow")) +
  labs(x = x, y = y)
```

```{r}
#Add k-means
bl62 %>%
  select(-aa) %>%
  kmeans(centers = 6, iter.max = 1000, nstart = 10) %>%
  augment(bl62_pca_aug) %>% 
  head
```

 
